language: python
python:
  - "3.6"
  - "3.7"

# command to install dependencies
# pip locked to version in prod170926
install:
  - pip install pip==9.0.1
  - pip install cython
  - pip install -U -r requirements.txt pytest-mock snapshottest .
# command to run tests
script:
  - pytest

cache: pip

jobs:
  include:
    - name: "production dependencies"
      if: type = pull_request
      script:
        - pip check
    - name: "development dependencies"
      if: type = pull_request
      script:
        - pip install -U -r requirements-dev.txt .
        - pip check
    - name: "coverage"
      if: NOT type = pull_request
      script:
        - pip install --upgrade pip
        - pip install -U -r requirements-dev.txt .
        - coverage run --branch --omit="*.html" --source "$(basename "$PWD")" setup.py test
        - coveralls
    - name: "code formatting"
      if: type = pull_request
      script:
        - pip install --upgrade pip
        - pip install black
        - git --no-pager diff --name-only --diff-filter=AM $TRAVIS_COMMIT_RANGE | grep ".py" | xargs black --check
    - name: "linting"
      if: type = pull_request
      script:
        - pip install --upgrade pip
        - pip install -U -r requirements-dev.txt
        - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

notifications:
  email: never
