# config file for automatic testing at travis-ci.org
language: python

python:
  - "3.4"
  - "2.7"

install:
  # install dependencies
  - pip install -r requirements/development.txt

  # install your own package + executables
  - pip install --editable .

script:
  # command to run tests and collect test coverage
  - coverage run --source taboo setup.py test

after_success:
  coveralls
