# config file for automatic testing at travis-ci.org
language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt -r requirements-dev.txt .

    - pip check

before_script:
    - git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint

script:
  # command to run tests and collect test coverage
  - coverage run --source genotype setup.py test

after_success:
  coveralls

notifications:
    email: never
