"""link plate with analysis

Revision ID: 21ef5ce15822
Revises: 88fa93c68dab
Create Date: 2016-12-05 15:12:49.067536

"""

# revision identifiers, used by Alembic.
revision = '21ef5ce15822'
down_revision = '88fa93c68dab'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('plate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'analysis', 'plate', ['plate_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis', type_='foreignkey')
    op.drop_column('analysis', 'plate_id')
    ### end Alembic commands ###
