"""initial structure

Revision ID: b1c09a577a3d
Revises: 
Create Date: 2016-11-29 06:25:55.467318

"""

# revision identifiers, used by Alembic.
revision = 'b1c09a577a3d'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
