name: Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.6.0
      - uses: actions/setup-python@v4.3.1
      - uses: psf/black@stable
