name: Publish to PyPI

on:
  release:
    types:
      - created

jobs:
  build-n-publish:
    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Build and Publish Distribution to PyPI 📦
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          poetry publish --no-interaction --build \
            --username $PYPI_USERNAME \
            --password $PYPI_PASSWORD
